#!/bin/bash

# Variables
REMOTE_USER="b"
REMOTE_HOST="192.168.0.105"
REMOTE_PORT="8888"
LOCAL_PORT="8888"
CONDA_ENV="$1"  # Conda environment name passed as argument
TOKEN="$2"

if [ -z "$CONDA_ENV" ]; then
  echo "Error: Please provide the Conda environment name as an argument."
  echo "Usage: $0 <conda_env>"
  exit 1
fi

if [ -z "$TOKEN" ]; then
  echo "Error: Please provide the token of server as an argument."
  echo "Usage: $0 <token>"
  exit 1
fi

# Step 1: Stop Jupyter Notebook on the remote server
echo "Stopping Jupyter Notebook on the remote server in Conda environment '${CONDA_ENV}'..."
ssh ${REMOTE_USER}@${REMOTE_HOST} "
    eval \"\$(/usr/src/any/anaconda3/bin/conda shell.zsh hook)\" && 
    conda activate ${CONDA_ENV} &&
    pkill -f 'jupyter-notebook --NotebookApp.token="${TOKEN}" --no-browser --port=${REMOTE_PORT}'
"

if [ $? -eq 0 ]; then
  echo "Jupyter Notebook stopped successfully on the remote server."
else
  echo "Failed to stop Jupyter Notebook on the remote server. Please check manually."
  exit 1
fi

